### ISSUE TITLE
Issues with the memcached driver

### ISSUE THREAD

**Issue by koldkoder** [hapijs/catbox-memcached#19]
I have seen production issue with the memcached driver. The driver hangs if the memcached instance has a network partition. This is intermittent behavior. I was thinking of upgrading the underlying driver to this memjs, which redislabs has backed on their blog https://redislabs.com/node-js-memcached.  Any thoughts on that kind of change?

**Comment by chapel** [comment]
I am not actively maintaining this at the moment, and looking for someone
to take it over. With that said, I would bet that the driver used now needs
re-evaluation and if memjs is better, maintained or otherwise please submit
a PR.

Note the contribution expectations and make sure tests pass appropriately.
Of course breaking changes can be made with the appropriate version change.

**Comment by koldkoder** [comment]
Here is the pull request. https://github.com/hapijs/catbox-memcached/pull/20

**Comment by koldkoder** [comment]
@chapel would you consider the pull request with the updated driver. let me know. thanks.
